# Generated by Django 4.0.1 on 2024-02-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='desigination',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
