# Generated by Django 4.0.1 on 2024-02-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee_desigination'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelogs',
            name='phonenumber',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
