# Generated by Django 4.0.1 on 2024-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_calllogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllogs',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
