# Generated by Django 4.0.1 on 2024-02-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_calllogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelogs',
            name='sms_info',
            field=models.CharField(max_length=2000),
        ),
    ]
