# Generated by Django 4.0.1 on 2024-02-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_messagelogs_sms_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='messagelogs',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
