# Generated by Django 4.0.1 on 2024-02-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_location_date_alter_messagelogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='place',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='place',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
