# Generated by Django 4.0.1 on 2024-03-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_simchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.CharField(max_length=300)),
                ('longitude', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=300)),
                ('notification', models.CharField(max_length=300)),
                ('EMPLOYEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
    ]
