# Generated by Django 4.0.1 on 2024-03-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_zonechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilesettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdcard', models.CharField(max_length=300)),
                ('ringmode', models.CharField(max_length=300)),
                ('brightness', models.CharField(max_length=300)),
                ('touchmode', models.CharField(max_length=300)),
                ('EMPLOYEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
    ]
