# Generated by Django 4.0.1 on 2024-03-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_profilesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='wallpaper',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
