# Generated by Django 4.0.1 on 2024-03-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_profilesettings_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedwork',
            name='description',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
