# Generated by Django 4.0.1 on 2024-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_allocatedwork_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedwork',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
