# Generated by Django 4.0.1 on 2024-03-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_allocatedwork_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocatedwork',
            old_name='date',
            new_name='Date',
        ),
    ]
