# Generated by Django 4.0.1 on 2024-03-20 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_allocatedwork_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedwork',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
