# Generated by Django 4.0.1 on 2024-03-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_allocatedwork_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatedwork',
            name='date',
        ),
    ]
