# Generated by Django 4.0.1 on 2024-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_allocatedwork_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedwork',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
