# Generated by Django 4.0.1 on 2024-03-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_allocatedwork_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Simchange',
        ),
    ]
