# Generated by Django 4.0.1 on 2024-03-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_simchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='EMPLOYEE',
        ),
    ]
