# Generated by Django 4.0.1 on 2024-03-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_zone_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='EMPLOYEE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
            preserve_default=False,
        ),
    ]
