# Generated by Django 4.0.1 on 2024-03-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_zone_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatedwork',
            name='EMPLOYEE',
        ),
        migrations.RemoveField(
            model_name='allocatedwork',
            name='WORK',
        ),
        migrations.RemoveField(
            model_name='calllogs',
            name='EMPLOYEE',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='EMPLOYEE',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='LOGIN',
        ),
        migrations.RemoveField(
            model_name='location',
            name='EMPLOYEE',
        ),
        migrations.RemoveField(
            model_name='messagelogs',
            name='EMPLOYEE',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='profilesettings',
            name='EMPLOYEE',
        ),
        migrations.RemoveField(
            model_name='report',
            name='EMPLOYEE',
        ),
        migrations.RemoveField(
            model_name='simchange',
            name='EMPLOYEE',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='EMPLOYEE',
        ),
        migrations.RemoveField(
            model_name='zonechange',
            name='EMPLOYEE',
        ),
        migrations.DeleteModel(
            name='AllocatedWork',
        ),
        migrations.DeleteModel(
            name='CallLogs',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='MessageLogs',
        ),
        migrations.DeleteModel(
            name='Profilesettings',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Simchange',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.DeleteModel(
            name='Zonechange',
        ),
    ]
