# Generated by Django 4.0.1 on 2024-03-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_employee_profile_work_zonechange_zone_simchange_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatedwork',
            name='description',
        ),
    ]
