# Generated by Django 4.0.1 on 2024-03-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_allocatedwork_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='c_incident',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
